spring:
  application:
    name: firesafety #???? ??
  datasource: # ?????? ?? ??
    url: jdbc:mysql://localhost:3306/firesafety
    username: root
    password: qaws7579

mybatis: # Mybatis ??
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml #xml?? ??
